# Inventaire Ansible — 2 serveurs gérés depuis le nœud de contrôle (Ubuntu Desktop)
# Remplacer les IP par celles de vos VM (réseau NAT).

[https]
apache01 ansible_host=192.168.X.X

[glpi]
glpi01 ansible_host=192.168.X.X

[all:vars]
ansible_user=CHANGE_ME
